### ISSUE TITLE
Why did the experiment select the known class as the positive sample?

### ISSUE THREAD

**Issue by leyiweb** [iCGY96/ARPL#3]
I noticed that in the experimental code, you use known class as a positive sample to calculate related indicators. This does not seem to be consistent with the openset/ODD field. Most of the openset open source codes choose unknown class as a positive sample, such as the OSRCI method you compared.

**Comment by iCGY96** [comment]
Our main indicators refer to the following link code:
https://github.com/pokaxpoka/deep_Mahalanobis_detector/blob/master/calculate_log.py

I hope it can help you.

**Comment by leyiweb** [comment]
Thank you very much for your answer. 
I browsed the article you referred to. It doesn't seem to compare with the work in the openset/ODD field, so it doesn't matter which sample is selected as the positive sample.
But usually the related openset methods are compared in the article, and the consistency of the experiment needs to be maintained.

**Comment by iCGY96** [comment]
The indicators of the article [1] are for OOD detection. I think it can serve as a reference for the evaluation.

The consistency of most open set methods should also be maintained. The results of the related open set methods in our paper are from CGDL and CA2E. However, the source code of many open set works that could not be found, such as CA2E and CGDL. What is the consistency remains to be confirmed. For better comparison, we not only provide the AUROC comparison but also provide the new evaluation OSCR for a fair comparison.

If you have a standard open set evaluation code, I hope you could provide an open-source code. This will contribute a lot to solve the chaotic evaluation of OSR.

[1] A Simple Unified Framework for Detecting Out-of-Distribution Samples and Adversarial Attacks
