### ISSUE TITLE
Hi, I send another email to you and to your lab :-) looking forward to your reply.

### ISSUE THREAD

**Issue by Jing--Li** [iCGY96/ARPL#5]

**Comment by iCGY96** [comment]
We have received your email. The partition of folders is the corresponding annotation information.

I hope it can help you!

**Comment by Jing--Li** [comment]
Thank you. I understand the directory names can act as class labels. But folder names like "R0-M00" do not offer human-readable information. I need the labels like Boeing737, A320 to get a corresponding relationship with FGVC-Aircraft. I guess these human-readable categories should be available when you construct this new dataset. Would you like to provide the literal meaning corresponding to these folder names? For example, R0-M00 is the A330 class, R0-M01 is the Boeing737 class, and so on.

**Comment by iCGY96** [comment]
Annotation data will be sent to you by email soon! Thanks!
